- name: install and run nginx
  hosts: web
  become: yes #become = sudo
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes